Repository E-Edu/task, pull requests merged in 2020-04, with the labels that each got.

#157 Issue/131
  src/main/java/de/themorpheus/edu/taskservice/controller/TaskController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/VotingController.java
  src/main/java/de/themorpheus/edu/taskservice/database/repository/VotingRepository.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/TaskEndpoint.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/VoteTaskDTO.java
Labels: feature, rest

#179 Everything will now be checked before deleting (#152)
  src/main/java/de/themorpheus/edu/taskservice/controller/DifficultyController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/LectureController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/ModuleController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/SubjectController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/TaskController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/TaskTypeController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/MultipleChoiceSolutionController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/WordsaladSolutionController.java
  src/main/java/de/themorpheus/edu/taskservice/database/repository/DifficultyRepository.java
  src/main/java/de/themorpheus/edu/taskservice/database/repository/LectureRepository.java
  src/main/java/de/themorpheus/edu/taskservice/database/repository/ModuleRepository.java
  src/main/java/de/themorpheus/edu/taskservice/database/repository/SubjectRepository.java
  src/main/java/de/themorpheus/edu/taskservice/database/repository/TaskTypeRepository.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/LectureEndpoint.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/ModuleEndpoint.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/SubjectEndpoint.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/TaskEndpoint.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/TaskTypeEndpoint.java
Labels: improvement, rest

#184 Everything will now be checked before deleting (#152)
  src/main/java/de/themorpheus/edu/taskservice/controller/DifficultyController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/LectureController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/ModuleController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/SubjectController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/TaskController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/TaskTypeController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/MultipleChoiceSolutionController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/WordsaladSolutionController.java
  src/main/java/de/themorpheus/edu/taskservice/database/repository/DifficultyRepository.java
  src/main/java/de/themorpheus/edu/taskservice/database/repository/LectureRepository.java
  src/main/java/de/themorpheus/edu/taskservice/database/repository/ModuleRepository.java
  src/main/java/de/themorpheus/edu/taskservice/database/repository/SubjectRepository.java
  src/main/java/de/themorpheus/edu/taskservice/database/repository/TaskTypeRepository.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/LectureEndpoint.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/ModuleEndpoint.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/SubjectEndpoint.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/TaskEndpoint.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/TaskTypeEndpoint.java
Labels: feature

#197 Issue/196
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/MultipleChoiceSolutionController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/WordsaladSolutionController.java
  src/main/java/de/themorpheus/edu/taskservice/database/repository/solution/MultipleChoiceSolutionRepository.java
  src/main/java/de/themorpheus/edu/taskservice/database/repository/solution/SolutionWordsaladRepository.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/TaskTypeEndpoint.java
Labels: bug

#205 Issue/204
  src/main/java/de/themorpheus/edu/taskservice/endpoint/TaskEndpoint.java
Labels: improvement

#203 Added function to get SolutionType of Task (#139)
  src/main/java/de/themorpheus/edu/taskservice/controller/TaskController.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/TaskEndpoint.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/response/GetSolutionTypeResponseDTO.java
Labels: improvement

#216 Fixed Error on task delete (#182)
  src/main/java/de/themorpheus/edu/taskservice/controller/TaskController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/Solution.java
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/SolutionController.java
  src/main/java/de/themorpheus/edu/taskservice/database/repository/TaskRepository.java
Labels: improvement

#215 Added TopicConnectionSolution and SimpleEquationSolution (#150)
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/FreestyleSolutionController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/ImageSolutionController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/MultipleChoiceSolutionController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/SimpleEquationSolutionController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/Solution.java
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/SolutionController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/TopicConnectionSolutionController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/WordsaladSolutionController.java
  src/main/java/de/themorpheus/edu/taskservice/database/model/solution/SimpleEquationSolutionModel.java
  src/main/java/de/themorpheus/edu/taskservice/database/model/solution/SimpleEquationSolutionResultModel.java
  src/main/java/de/themorpheus/edu/taskservice/database/model/solution/TopicConnectionSolutionModel.java
  src/main/java/de/themorpheus/edu/taskservice/database/repository/solution/SimpleEquationSolutionRepository.java
  src/main/java/de/themorpheus/edu/taskservice/database/repository/solution/SimpleEquationSolutionResultRepository.java
  src/main/java/de/themorpheus/edu/taskservice/database/repository/solution/TopicConnectionSolutionRepository.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/request/solution/CheckSimpleEquationSolutionRequestDTO.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/request/solution/CheckTopicConnectionSolutionRequestDTO.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/request/solution/CheckTopicConnectionSolutionRequestDTOModel.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/request/solution/CreateTopicConnectionSolutionRequestDTO.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/request/solution/UpdateSimpleEquationSolutionRequestDTO.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/request/solution/UpdateSimpleEquationSolutionRequestDTOModel.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/response/solution/CheckSimpleEquationSolutionResponseDTO.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/response/solution/CheckSimpleEquationSolutionResponseDTOModel.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/response/solution/CheckTopicConnectionSolutionResponseDTO.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/response/solution/CheckTopicConnectionSolutionResponseDTOModel.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/response/solution/CreateSimpleEquationSolutionRequestDTO.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/response/solution/CreateSimpleEquationSolutionResponseDTO.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/response/solution/CreateSimpleEquationSolutionResponseDTOModel.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/response/solution/CreateTopicConnectionSolutionResponseDTO.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/response/solution/GetAllTopicConnectionSolutionsResponseDTO.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/response/solution/GetAllTopicConnectionSolutionsResponseDTOModel.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/response/solution/GetTopicConnectionSolutionResponseDTO.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/response/solution/UpdateSimpleEquationSolutionResponseDTO.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/response/solution/UpdateSimpleEquationSolutionResponseDTOModel.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/solution/SimpleEquationSolutionEndpoint.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/solution/TopicConnectionSolutionEndpoint.java
  src/main/java/de/themorpheus/edu/taskservice/util/Constants.java
Labels: feature

#226 Adapted MultipleChoiceSolutions (#225)
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/MultipleChoiceSolutionController.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/response/solution/GetAllMultipleChoiceSolutionsResponseDTO.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/response/solution/GetAllMultipleChoiceSolutionsResponseDTOModel.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/solution/MultipleChoiceSolutionEndpoint.java
Labels: documentation, improvement, rest

#227 Issue 211,185,186,23
  src/main/java/de/themorpheus/edu/taskservice/controller/TaskController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/VotingController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/FreestyleSolutionController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/ImageSolutionController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/Solution.java
  src/main/java/de/themorpheus/edu/taskservice/controller/user/UserDataController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/user/UserDataHandler.java
  src/main/java/de/themorpheus/edu/taskservice/database/model/TaskModel.java
  src/main/java/de/themorpheus/edu/taskservice/database/model/VotingModel.java
  src/main/java/de/themorpheus/edu/taskservice/database/model/solution/UserFreestyleSolutionModel.java
  src/main/java/de/themorpheus/edu/taskservice/database/model/solution/UserImageSolutionModel.java
  src/main/java/de/themorpheus/edu/taskservice/database/repository/TaskRepository.java
  src/main/java/de/themorpheus/edu/taskservice/database/repository/VotingRepository.java
  src/main/java/de/themorpheus/edu/taskservice/database/repository/solution/UserFreestyleSolutionRepository.java
  src/main/java/de/themorpheus/edu/taskservice/database/repository/solution/UserImageSolutionRepository.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/TaskEndpoint.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/UserDataEndpoint.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/response/GetAllTasksByUserResponseDTO.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/response/GetUserDataResponseDTO.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/response/GetUserDataResponseDTOModel.java
  src/main/java/de/themorpheus/edu/taskservice/util/Constants.java
Labels: documentation, feature, improvement, rest

#229 Deleted CLI (#54)
  src/main/java/de/themorpheus/edu/taskservice/TaskServiceApplication.java
  src/main/java/de/themorpheus/edu/taskservice/cli/CLIManager.java
  src/main/java/de/themorpheus/edu/taskservice/cli/Command.java
  src/main/java/de/themorpheus/edu/taskservice/cli/CommandExecuter.java
  src/main/java/de/themorpheus/edu/taskservice/cli/Options.java
  src/main/java/de/themorpheus/edu/taskservice/cli/commands/HelpCommand.java
Labels: improvement

#208 Added publish if user sent a freestyle/image solution (#207)
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/FreestyleSolutionController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/ImageSolutionController.java
  src/main/java/de/themorpheus/edu/taskservice/pubsub/dto/UserSentFreestyleSolutionDTO.java
  src/main/java/de/themorpheus/edu/taskservice/pubsub/dto/UserSentImageSolutionDTO.java
Labels: feature

#228 Added get user solution
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/FreestyleSolutionController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/ImageSolutionController.java
  src/main/java/de/themorpheus/edu/taskservice/database/model/solution/UserFreestyleSolutionModel.java
  src/main/java/de/themorpheus/edu/taskservice/database/model/solution/UserImageSolutionModel.java
  src/main/java/de/themorpheus/edu/taskservice/database/repository/solution/UserFreestyleSolutionRepository.java
  src/main/java/de/themorpheus/edu/taskservice/database/repository/solution/UserImageSolutionRepository.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/response/solution/GetAllUserFreestyleSolutionsResponseDTO.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/response/solution/GetAllUserFreestyleSolutionsResponseDTOModel.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/response/solution/GetAllUserImageSolutionResponseDTO.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/response/solution/GetAllUserImageSolutionsResponseDTOModel.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/solution/FreestyleSolutionEndpoint.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/solution/ImageSolutionEndpoint.java
  src/main/java/de/themorpheus/edu/taskservice/util/Constants.java
Labels: Improvement, Rest

#224 Added task done
  src/main/java/de/themorpheus/edu/taskservice/controller/TaskController.java
  src/main/java/de/themorpheus/edu/taskservice/database/model/TaskDoneModel.java
  src/main/java/de/themorpheus/edu/taskservice/database/repository/TaskDoneRepository.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/TaskEndpoint.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/response/GetMarkTaskAsDoneResponseDTO.java
  src/main/java/de/themorpheus/edu/taskservice/util/Constants.java
Labels: Feature, Rest

#212 Added UserBan
  src/main/java/de/themorpheus/edu/taskservice/controller/TaskController.java
  src/main/java/de/themorpheus/edu/taskservice/database/model/UserBanModel.java
  src/main/java/de/themorpheus/edu/taskservice/database/repository/UserBanRepository.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/TaskEndpoint.java
  src/main/java/de/themorpheus/edu/taskservice/pubsub/dto/UserBanDTO.java
  src/main/java/de/themorpheus/edu/taskservice/pubsub/sub/UserBanSubscriber.java
Labels: Improvement, PubSub, Rest

#239 Added ExceptionHandler (#230) (Build will fail, waiting for #210 (#236))
  src/main/java/de/themorpheus/edu/taskservice/spring/RestControllerExceptionHandler.java
Labels: Improvement

#251 Added language column for task and taskGroup (#246)
  src/main/java/de/themorpheus/edu/taskservice/controller/TaskController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/TaskGroupController.java
  src/main/java/de/themorpheus/edu/taskservice/database/model/TaskGroupModel.java
  src/main/java/de/themorpheus/edu/taskservice/database/model/TaskModel.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/request/CreateTaskGroupRequestDTO.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/request/CreateTaskRequestDTO.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/request/UpdateTaskGroupRequestDTO.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/request/UpdateTaskRequestDTO.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/response/TaskGroupResponseDTO.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/response/TaskResponseDTO.java
Labels: Improvement

#250 Added feature on TopicConnectionSolutions that they can have no connection (#214)
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/TopicConnectionSolutionController.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/request/solution/CreateTopicConnectionSolutionRequestDTO.java
Labels: Improvement

#243 Added Pagination Feature (#88)
  docker-compose.yml
  src/main/java/de/themorpheus/edu/taskservice/TaskServiceApplication.java
  src/main/java/de/themorpheus/edu/taskservice/controller/TaskController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/TaskGroupController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/ImageSolutionController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/MultipleChoiceSolutionController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/SimpleEquationSolutionController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/TopicConnectionSolutionController.java
  src/main/java/de/themorpheus/edu/taskservice/controller/solution/WordsaladSolutionController.java
  src/main/java/de/themorpheus/edu/taskservice/database/repository/TaskGroupRepository.java
  src/main/java/de/themorpheus/edu/taskservice/database/repository/TaskRepository.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/TaskEndpoint.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/TaskGroupEndpoint.java
  src/main/java/de/themorpheus/edu/taskservice/util/PaginationManager.java
Labels: Feature, Rest
