Repository E-Edu/task, pull requests merged in 2020-03, with the labels that each got.

#17 Issue/8 Create ER Diagram
  .docs/ER_Diagram_Task_Database.xml
  .docs/ER_Diagram_Task_MS_Database.png
Labels: documentation

#28 Issue/2 Cli Basic Setup
  pom.xml
  src/main/java/de/themorpheus/edu/cli/CLIManager.java
  src/main/java/de/themorpheus/edu/cli/Command.java
  src/main/java/de/themorpheus/edu/cli/CommandExecuter.java
  src/main/java/de/themorpheus/edu/cli/Options.java
  src/main/java/de/themorpheus/edu/cli/commands/HelpCommand.java
  src/main/java/de/themorpheus/edu/taskservice/TaskServiceApplication.java
Labels: feature

#42 Issue/3
  README.md
  docker-compose.yml
Labels: feature

#51 Implemented lecture model
  src/main/java/de/themorpheus/edu/taskservice/database/model/LectureModel.java
Labels: feature

#87 Issue/18
  src/main/java/de/themorpheus/edu/taskservice/controller/TaskController.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/TaskEndpoint.java
Labels: feature, rest

#102 Issue/24
  src/main/java/de/themorpheus/edu/taskservice/controller/TaskController.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/TaskEndpoint.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/dto/UpdateTaskDTO.java
Labels: feature, rest

#103 Issue/95
  src/main/java/de/themorpheus/edu/taskservice/controller/SubjectController.java
  src/main/java/de/themorpheus/edu/taskservice/endpoint/SubjectEndpoint.java
  src/main/java/de/themorpheus/edu/taskservice/util/Error.java
  src/main/java/de/themorpheus/edu/taskservice/util/i18n.java
Labels: feature, rest
